//
//  StaticPlantDateStore.swift
//  PlantCare
//
//  Created by Laura Gongaware on 7/12/22.
//

import Foundation

class StaticPlantDataStore {
    static var staticplants: [StaticPlant] {
        
        let monstera = StaticPlant(plantName: "Monstera", scientificName: "Monstera deliciosa", water: 3, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", toxicity: "yes", staticImage: "monstera")
        
        let pilea = StaticPlant(plantName: "Pilea", scientificName: "Pilea peperomioides", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "no", staticImage: "pilea.png")
        
        let fiddleleaffig = StaticPlant(plantName: "Fiddleleaf Fig", scientificName: "Ficus lyrata", water: 4, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "fiddleleaffig")
        
        let snakeplant = StaticPlant(plantName: "Snake Plant", scientificName: "Sansevieria trifasciata", water: 2, sunlight: 2, description: "Sansevier am, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Exce", toxicity: "yes", staticImage: "snakeplant")
        
        let succulent = StaticPlant(plantName: "Succulents", scientificName: "various", water: 1, sunlight: 5, description: "am, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Exce", toxicity: "Yes", staticImage: "succulent.png")
        
        let spiderplant = StaticPlant(plantName: "Spider Plant", scientificName: "Chlorophytum comosum", water: 3, sunlight: 3, description: "lor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occae", toxicity: "yes", staticImage: "spiderplant")
        
        let pothos = StaticPlant(plantName: "Pothos", scientificName: "Epipremnum sp.", water: 3, sunlight: 3, description: "onsectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occa", toxicity: "yes", staticImage: "pothos")
        
        let prayerplant = StaticPlant(plantName: "Prayer Plant", scientificName: "Maranta leuconeura", water: 4, sunlight: 2, description: "adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo cons", toxicity: "No", staticImage: "prayerplant.png")
        
        let philodendron = StaticPlant(plantName: "Philodendron", scientificName: "Philodendron sp.", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "philodendron.png")
        
        let stringofpearls = StaticPlant(plantName: "String of Pearls", scientificName: "Senecio Rowleyanus", water: 2, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "stringofpearls")
        
        let catcus = StaticPlant(plantName: "Cactus", scientificName: "various", water: 1, sunlight: 5, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "cactus.png")
        
        let peacelily = StaticPlant(plantName: "Peace Lily", scientificName: "Spathiphyllum cochlearispathum", water: 4, sunlight: 5, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "peacelily.png")
        
        let alocasia = StaticPlant(plantName: "Alocasia", scientificName: "Alocasia sp.", water: 4, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "alocasia")
        
        let calathea = StaticPlant(plantName: "Calathea", scientificName: "Calathea sp.", water: 4, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "no", staticImage: "calathea.png")
        
        let africanviolet = StaticPlant(plantName: "African Violet", scientificName: "Saintpaulia ionntha", water: 3, sunlight: 4, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "no", staticImage: "africanviolet.png")
        
        let orchid = StaticPlant(plantName: "Orchid", scientificName: "Orchidaceae", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "no", staticImage: "orchid.png")
        
        let diffenbachia = StaticPlant(plantName: "Diffenbachia", scientificName: "Diffenbachia sp.", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "diffenbachia.png")
        
        let tradescantia = StaticPlant(plantName: "Wandering Jewel", scientificName: "Tradescantia sp.", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "tradescantia.png")
        
        let zzplant = StaticPlant(plantName: "ZZ Plant", scientificName: "Zamioculcas zamiifolia", water: 2, sunlight: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "zzplant.png")
        
        let arrowheadplant = StaticPlant(plantName: "Arrowhead Plant", scientificName: "Syngonium podophyllum", water: 3, sunlight: 3, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no", toxicity: "yes", staticImage: "arrowheadplant.png")
        
        return [monstera, pilea, fiddleleaffig, snakeplant, succulent, spiderplant, pothos, prayerplant, philodendron, stringofpearls, catcus, peacelily, alocasia, calathea, africanviolet, orchid, diffenbachia, tradescantia, zzplant, arrowheadplant]
    }
    
}
